library(rjson)

# Function for extracting structured Abaqus displacement data from a json file
# This function only works if the number of frames is constant across samples,
# and the number of nodes is constant across frames, i.e. the data has 
# consistent structure. Data is structured as:
# in_struct["Sample"][[i]]["Frame"][[j]]["Displacements"]
#                                       ["Increment"]
#                                       ["RFs"]

extract_const_frame <- function(in_struct, disp_str) {
  # Assume number of frames is the same for each sample, and the number of nodes 
  # the same for each frame. Add error terms to spot if this isn't the case
  n_nodes = length(in_struct$Sample[[1]]$Frame[[1]]$Displacements) # Number of nodes
  n_frames = length(in_struct$Sample[[1]]$Frame) # Number of frames
  m = length(in_struct$Sample) # Number of samples
  out_mat = matrix(NA,nrow = n_nodes*n_frames*length(disp_str), ncol = m)
  # Assign a column index depending on which displacement component is of interest
  col_ind = sapply(disp_str, function(x) switch(x, "u"=1, "v"=2, "w"=3))
  print(col_ind)
  
  # Loop over output for all samples
  for (i in 1:length(in_struct$Sample)){
    # Extract a list of frames for each sample
    sample_i = in_struct$Sample[[i]]$Frame
    if (length(sample_i) != n_frames){
      # Flag error if the number of frames is different in the current sample
      stop("There are a different number of frames across samples")
    } 
    disp_i = matrix(data = NA, nrow=0, ncol=3)
    # Loop over each frame and extract the displacement
    for (j in 1:n_frames){
      frame_j = do.call(rbind, sample_i[[j]]$Displacements)
      if (nrow(frame_j) != n_nodes){
        # Flag error if the number of nodes is different in the current frame
        stop("There are a different number of nodes across samples")
      } 
      # the outputs of each frame are concatenated
      disp_i = rbind(disp_i, frame_j)
    }
    # Store the component(s) of interest to the matrix of model outputs
    for (j in 1:length(col_ind)){
      out_mat[((j-1)*(n_nodes*n_frames)+1):(j*n_nodes*n_frames),i] = disp_i[,col_ind[j]]
    }
    # out_mat[,i] = disp_i[,col_ind]
  }
  
  return(list(out_mat,n_nodes,n_frames))
}

# converts the basis and mean functions generated by the nonlinear emulator 
# code, trained using data with identical incrementation across samples, to a 
# json with structure
#out_scruct["Frame"][[i]]["Bases"]
#                        ["Training_Data_Mean"]
# where "Bases" contains an n_nodes list of n_bases basis values
basis_mean_to_json <- function(n_frames, n_nodes, K, mu_dt) {
  # Initialise list
  out_list <- list(list())
  names(out_list) <- "Frame"
  out_list$Frame <- vector(mode="list", length=n_frames)
  for (i in 1:n_frames){
    # Extract bases for the current frame
    K_i = K[((i-1)*n_nodes+1):(i*n_nodes),]
    # Also output model mean to the same json
    mu_i = mu_dt[((i-1)*n_nodes+1):(i*n_nodes)]
    out_list$Frame[[i]] = list(vector(mode="list", length=n_nodes), mu_i)
    names(out_list$Frame[[i]]) = c("Bases", "Training_Data_Mean")
    for (j in 1:n_nodes){
      out_list$Frame[[i]]$Bases[[j]] = K_i[j,]
    }
  }
  out_json = toJSON(out_list)
  
  return(out_json)
}

# Converts the emulator predictions generated by the nonlinear emulator code, 
# trained using data with identical incrementations across samples, to a json 
# with structure: out_scruct["Prediction"][[i]]["Frame"][[j]]["QoI_1"]
#                                                            ["QoI_2"] etc
# where quantity of interest are contained within input list in_list, and can
# take values "eta_mu", "eta_sigma", "eta_sam", "eta_mu_mu", "eta_sigma_mu" and
# "eta_sam_mu". The first three quantities are array containing multiple 
# posterior samples, and have a subheading "Posterior_Samples" with length n_post_sam
gp_pred_to_json <- function(in_list, n_frames, n_nodes, n_pred=1, n_post_sam=1) {
  # Initialise list
  out_list <- list(list())
  names(out_list) = "Prediction"
  if (n_pred > 1){
    out_list$Prediction <- vector(mode="list", length=n_pred)
  }
  # Loop over predictions
  for (i in 1:n_pred){
    out_list$Prediction[[i]] = list(list())
    names(out_list$Prediction[[i]]) = "Frame"
    out_list$Prediction[[i]]$Frame = vector(mode="list", length=n_frames)
    # Loop over frames
    for (j in 1:n_frames){
      out_list$Prediction[[i]]$Frame[[j]] = vector(mode="list", length(in_list))
      names(out_list$Prediction[[i]]$Frame[[j]]) = names(in_list)
      for (k in 1:length(in_list)){
        # If output quantity contains multiple posterior samples, the list will
        # contain a sub-list of posterior samples
        if (names(in_list)[k] == "eta_mu"      |
            names(in_list)[k] == "eta_sigma"   |
            names(in_list)[k] == "eta_sam"     |
            names(in_list)[k] == "w_star_mu"   |
            names(in_list)[k] == "w_star_sam"){
          out_list$Prediction[[i]]$Frame[[j]][[k]] = list(list())
          names(out_list$Prediction[[i]]$Frame[[j]][[k]]) = "Posterior_Sample"
          out_list$Prediction[[i]]$Frame[[j]][[k]]$Posterior_Sample = vector(mode="list", length=n_post_sam)
          # Loop over posterior samples
          for (l in 1:n_post_sam){
            if (n_pred > 1) {
              out_ijl = in_list[[k]][((j-1)*n_nodes+1):(j*n_nodes),l,i]
            } else {
              out_ijl = in_list[[k]][((j-1)*n_nodes+1):(j*n_nodes),l]
            }
            # Extract output for relevant list entry
            out_list$Prediction[[i]]$Frame[[j]][[k]]$Posterior_Sample[[l]] = out_ijl
          }
        } else {
          if (n_pred > 1) {
            out_ij = in_list[[k]][((j-1)*n_nodes+1):(j*n_nodes),i]
          } else {
            out_ij = in_list[[k]][((j-1)*n_nodes+1):(j*n_nodes)]
          }
          # Extract output for relevent list entry
          out_list$Prediction[[i]]$Frame[[j]][[k]] = out_ij
        }
      }
    }
  }
  # View(out_list$Prediction[[1]])
  # Collapse the first level of the list if there is only one prediction
  if (n_pred == 1){
    out_list = out_list$Prediction[[1]]
  }
  out_json = toJSON(out_list)
  return(out_json)
}
